site_name: gmirror - 常用软件CDN镜像下载
pages:
- "首页": index.md
- "关于我们": about.md
theme: readthedocs
repo_url: https://github.com/sinkcup/gmirror
site_favicon: favicon.ico
copyright: <a title="帮助我们：点击注册七牛，本站将获得流量供大家下载使用" href="https://portal.qiniu.com/signup?code=3lafkpsz7yes1" target="_blank"><img src="http://assets.qiniu.com/qiniu-transparent.png" alt="七牛云" /></a><a rel="nofollow" href="http://www.miitbeian.gov.cn/">苏ICP备15020382号-2</a>
    <script type="text/javascript">
        window.zhuge=window.zhuge||[];window.zhuge.methods="_init debug identify track trackLink trackForm page".split(" ");window.zhuge.factory=function(b){return function(){var a=Array.prototype.slice.call(arguments);a.unshift(b);window.zhuge.push(a);return window.zhuge}};for(var i=0;i<window.zhuge.methods.length;i++){var key=window.zhuge.methods[i];window.zhuge[key]=window.zhuge.factory(key)};window.zhuge.load=function(b,x){if(!document.getElementById("zhuge-js")){var a=document.createElement("script");a.type="text/javascript";a.id="zhuge-js";a.async=!0;a.src="https://zgsdk.37degree.com/zhuge-lastest.min.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c);window.zhuge._init(b,x)}}; window.zhuge.load('86a17a5f139042589ee72d51509c5ecb');
        function cmpVersion(a, b) {
            var i, cmp, len, re = /(\.0)+[^\.]*$/;
            a = (a + '').replace(re, '').split('.');
            b = (b + '').replace(re, '').split('.');
            len = Math.min(a.length, b.length);
            for( i = 0; i < len; i++ ) {
                cmp = parseInt(a[i], 10) - parseInt(b[i], 10);
                if( cmp !== 0 ) {
                    return cmp;
                }
            }
            return a.length - b.length;
        }
        var chromeLastestVersion = '51.0.2704.84';
        var start = window.navigator.userAgent.indexOf('Chrome/');
        if (start != -1) {
            var chromeUserVersion = window.navigator.userAgent.split('Chrome/')[1].split(' ')[0];
            var cmp = cmpVersion(chromeLastestVersion, chromeUserVersion);
            $("nav.wy-nav-side").append('<div style="color:#b3b3b3">你正在使用的是Chrome/' + chromeUserVersion + '</div>');
            var notice = "恭喜你，已经是最新版";
            if (cmp > 0) {
                notice = '请升级至最新版Chrome/' + chromeLastestVersion + '</div>';
            } else if (cmp < 0) {
                notice = '哇！比本站的版本还新，请<a href="https://github.com/sinkcup/gmirror" target="_blank">提交代码更新</a>';
            }
            $("nav.wy-nav-side").append('<div style="color:#fcfcfc">' + notice + '</div>');
        }
    </script>
